name: Test Action with Email Step

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f2001350@ds.study.iitm.ac.in
        run: echo "Hello, world!"
